export const FIND_RESULTS = "FIND_RESULTS";

export const SHOW_MESSAGE = "SHOW_MESSAGE";

export const ADD_RESULT_HISTORY = "ADD_RESULT_HISTORY";
export const SHOW_RESULT_HISTORY = "SHOW_RESULT_HISTORY";
export const HIDE_RESULT_HISTORY = "HIDE_RESULT_HISTORY ";